export const educations = [
  "High School",
  "Secondary School",
  "Diploma",
  "Associate's Degree",
  "A.A. (Associate of Arts)",
  "A.S. (Associate of Science)",
  "A.A.S. (Associate of Applied Science)",
  "A.F.A. (Associate of Fine Arts)",
  "A.B.A. (Associate of Business Administration)",
  "Bachelor's Degree",
  "B.A. (Bachelor of Arts)",
  "B.S. (Bachelor of Science)",
  "B.B.A. (Bachelor of Business Administration)",
  "B.E. (Bachelor of Engineering)",
  "B.Ed. (Bachelor of Education)",
  "B.F.A. (Bachelor of Fine Arts)",
  "B.Sc. (Bachelor of Science)",
  "B.Tech. (Bachelor of Technology)",
  "B.Com. (Bachelor of Commerce)",
  "B.Arch. (Bachelor of Architecture)",
  "B.Des. (Bachelor of Design)",
  "B.L.S. (Bachelor of Library Science)",
  "B.S.W. (Bachelor of Social Work)",
  "B.Pharm. (Bachelor of Pharmacy)",
  "B.C.A. (Bachelor of Computer Applications)",
  "B.I.T. (Bachelor of Information Technology)",
  "B.Agri. (Bachelor of Agriculture)",
  "B.Mus. (Bachelor of Music)",
  "B.P.E. (Bachelor of Physical Education)",
  "B.Sc.N. (Bachelor of Science in Nursing)",
  "B.Med. (Bachelor of Medicine)",
  "Master's Degree",
  "M.A. (Master of Arts)",
  "M.S. (Master of Science)",
  "M.B.A. (Master of Business Administration)",
  "M.Ed. (Master of Education)",
  "M.F.A. (Master of Fine Arts)",
  "M.Sc. (Master of Science)",
  "M.Tech. (Master of Technology)",
  "M.Com. (Master of Commerce)",
  "M.Arch. (Master of Architecture)",
  "M.Des. (Master of Design)",
  "M.L.S. (Master of Library Science)",
  "M.S.W. (Master of Social Work)",
  "M.Pharm. (Master of Pharmacy)",
  "M.C.A. (Master of Computer Applications)",
  "M.I.T. (Master of Information Technology)",
  "M.Agri. (Master of Agriculture)",
  "M.Mus. (Master of Music)",
  "M.P.E. (Master of Physical Education)",
  "M.Sc.N. (Master of Science in Nursing)",
  "M.Med. (Master of Medicine)",
  "Doctoral Degree",
  "Ph.D. (Doctor of Philosophy)",
  "Ed.D. (Doctor of Education)",
  "D.Sc. (Doctor of Science)",
  "D.B.A. (Doctor of Business Administration)",
  "D.M.A. (Doctor of Musical Arts)",
  "M.D. (Doctor of Medicine)",
  "J.D. (Juris Doctor)",
  "D.Litt. (Doctor of Letters)",
  "D.V.M. (Doctor of Veterinary Medicine)",
  "D.Pharm. (Doctor of Pharmacy)",
  "D.Eng. (Doctor of Engineering)",
  "D.Phil. (Doctor of Philosophy)",
  "Professional Certificate",
  "P.G. Diploma (Postgraduate Diploma)",
  "CFA (Chartered Financial Analyst)",
  "CPA (Certified Public Accountant)",
  "CMA (Certified Management Accountant)",
  "CISSP (Certified Information Systems Security Professional)",
  "CISA (Certified Information Systems Auditor)",
  "CFA (Chartered Financial Analyst)",
  "CFE (Certified Fraud Examiner)",
  "CPE (Continuing Professional Education)",
  "PRINCE2 (Projects in Controlled Environments)",
  "PMP (Project Management Professional)",
  "ITIL (Information Technology Infrastructure Library)",
  "Six Sigma Green Belt",
  "Six Sigma Black Belt",
  "AWS Certified Solutions Architect",
  "AWS Certified Developer",
  "AWS Certified SysOps Administrator",
  "MCSE (Microsoft Certified Solutions Expert)",
  "MCSD (Microsoft Certified Solutions Developer)",
  "MCSA (Microsoft Certified Solutions Associate)",
  "RHCE (Red Hat Certified Engineer)",
  "CCNA (Cisco Certified Network Associate)",
  "CCNP (Cisco Certified Network Professional)",
  "CISSP (Certified Information Systems Security Professional)",
  "PMP (Project Management Professional)",
  "ACP (Agile Certified Practitioner)",
  "CSM (Certified ScrumMaster)",
  "CSPO (Certified Scrum Product Owner)",
  "Lean Six Sigma Yellow Belt",
  "Lean Six Sigma Green Belt",
  "Lean Six Sigma Black Belt",
  "TOGAF (The Open Group Architecture Framework)",
  "Oracle Certified Professional",
  "Oracle Certified Master",
  "Google Cloud Certified - Professional Cloud Architect",
  "Google Cloud Certified - Professional Data Engineer",
  "Google Cloud Certified - Associate Cloud Engineer",
  "Certified Ethical Hacker (CEH)",
  "CompTIA A+",
  "CompTIA Network+",
  "CompTIA Security+",
  "CIPP (Certified Information Privacy Professional)",
  "CGEIT (Certified in the Governance of Enterprise IT)",
  "CRISC (Certified in Risk and Information Systems Control)",
  "CISM (Certified Information Security Manager)",
  "CGEIT (Certified in the Governance of Enterprise IT)",
  "CAPM (Certified Associate in Project Management)",
  "CSP (Certified Safety Professional)",
  "SHRM-CP (Society for Human Resource Management Certified Professional)",
  "SHRM-SCP (Society for Human Resource Management Senior Certified Professional)",
  "PHR (Professional in Human Resources)",
  "SPHR (Senior Professional in Human Resources)",
  "GPHR (Global Professional in Human Resources)",
  "Associate's Degree in Nursing (ADN)",
  "Bachelor of Science in Nursing (BSN)",
  "Master of Science in Nursing (MSN)",
  "Doctor of Nursing Practice (DNP)",
  "Clinical Nurse Specialist (CNS)",
  "Nurse Practitioner (NP)",
  "Certified Nurse Midwife (CNM)",
  "Certified Registered Nurse Anesthetist (CRNA)",
  "Bachelor of Engineering (BE)",
  "Master of Engineering (ME)",
  "Doctor of Engineering (DEng)",
  "Graduate",
  "10/12th Pass",
  "Intermediate",
  "BTech",
  "MCA (Master of Computer Applications)",
  "BCA (Bachelor of Computer Applications)",
  "Associate of Arts",
  "Associate of Science",
  "Associate of Applied Science",
  "Associate of Fine Arts",
  "Associate of Business Administration",
  "Bachelor of Arts",
  "Bachelor of Science",
  "Bachelor of Business Administration",
  "Bachelor of Engineering",
  "Bachelor of Education",
  "Bachelor of Fine Arts",
  "Bachelor of Science",
  "Bachelor of Technology",
  "Bachelor of Commerce",
  "Bachelor of Architecture",
  "Bachelor of Design",
  "Bachelor of Library Science",
  "Bachelor of Social Work",
  "Bachelor of Pharmacy",
  "Bachelor of Computer Applications",
  "Bachelor of Information Technology",
  "Bachelor of Agriculture",
  "Bachelor of Music",
  "Bachelor of Physical Education",
  "Bachelor of Science in Nursing",
  "Bachelor of Medicine",
  "Master of Arts",
  "Master of Science",
  "Master of Business Administration",
  "Master of Education",
  "Master of Fine Arts",
  "Master of Science",
  "Master of Technology",
  "Master of Commerce",
  "Master of Architecture",
  "Master of Design",
  "Master of Library Science",
  "Master of Social Work",
  "Master of Pharmacy",
  "Master of Computer Applications",
  "Master of Information Technology",
  "Master of Agriculture",
  "Master of Music",
  "Master of Physical Education",
  "Master of Science in Nursing",
  "Master of Medicine",
  "Doctor of Philosophy",
  "Doctor of Education",
  "Doctor of Science",
  "Doctor of Business Administration",
  "Doctor of Musical Arts",
  "Doctor of Medicine",
  "Juris Doctor",
  "Doctor of Letters",
  "Doctor of Veterinary Medicine",
  "Doctor of Pharmacy",
  "Doctor of Engineering",
  "Doctor of Philosophy",
  "Postgraduate Diploma",
  "Chartered Financial Analyst",
  "Certified Public Accountant",
  "Certified Management Accountant",
  "Certified Information Systems Security Professional",
  "Certified Information Systems Auditor",
  "Certified Fraud Examiner",
  "Continuing Professional Education",
  "Projects in Controlled Environments",
  "Project Management Professional",
  "Information Technology Infrastructure Library",
  "Six Sigma Green Belt",
  "Six Sigma Black Belt",
  "AWS Certified Solutions Architect",
  "AWS Certified Developer",
  "AWS Certified SysOps Administrator",
  "Microsoft Certified Solutions Expert",
  "Microsoft Certified Solutions Developer",
  "Microsoft Certified Solutions Associate",
  "Red Hat Certified Engineer",
  "Cisco Certified Network Associate",
  "Cisco Certified Network Professional",
  "Certified Information Systems Security Professional",
  "Project Management Professional",
  "Agile Certified Practitioner",
  "Certified ScrumMaster",
  "Certified Scrum Product Owner",
  "Lean Six Sigma Yellow Belt",
  "Lean Six Sigma Green Belt",
  "Lean Six Sigma Black Belt",
  "The Open Group Architecture Framework",
  "Oracle Certified Professional",
  "Oracle Certified Master",
  "Google Cloud Certified - Professional Cloud Architect",
  "Google Cloud Certified - Professional Data Engineer",
  "Google Cloud Certified - Associate Cloud Engineer",
  "Certified Ethical Hacker",
  "CompTIA A+",
  "CompTIA Network+",
  "CompTIA Security+",
  "Certified Information Privacy Professional",
  "Certified in the Governance of Enterprise IT",
  "Certified in Risk and Information Systems Control",
  "Certified Information Security Manager",
  "Certified Associate in Project Management",
  "Certified Safety Professional",
  "Society for Human Resource Management Certified Professional",
  "Society for Human Resource Management Senior Certified Professional",
  "Professional in Human Resources",
  "Senior Professional in Human Resources",
  "Global Professional in Human Resources",
  "Associate's Degree in Nursing",
  "Bachelor of Science in Nursing",
  "Master of Science in Nursing",
  "Doctor of Nursing Practice",
  "Clinical Nurse Specialist",
  "Nurse Practitioner",
  "Certified Nurse Midwife",
  "Certified Registered Nurse Anesthetist",
  "Bachelor of Engineering",
  "Master of Engineering",
  "Doctor of Engineering",
];
